const delay = 500
describe('Kiểm thử  thêm mới bệnh nhân không check combo box "Nghê nghiệp"', function() {
      
      it('Đăng nhập với tư cách trưởng cơ sở và vào trang "Thêm mới"', function(){
            cy.visit('/signin')
            cy.get('input[name=email]').type('admin_agency_10@gmail.com')
            cy.get('input[name=password]').type('Methadone@2017')
            cy.get('button[type=submit]').click()
            cy.url().should('include', '/main/dashboard1')
            cy.wait(delay)        
            cy.visit('/main/patients/860/detail/executive_info')
            cy.wait(delay) 
            cy.visit('/main/patients/new')            
      })

      it('Điền thông tin bệnh nhân trừ combo box "Nghề nghiệp"', function(){
            cy.get('input[autofocus]').first().focus().type("Tran Van B")
            cy.get('input[name="birth_date"]').first().focus().type("08/06/1995")
            cy.get('div[name="gender"]').first().click() 
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()
            cy.get('div[ng-model="patient.ethnicity_id"]').first().click()
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()
            cy.get('input[name="mobile_phone"]').type("0987393067")
            cy.get('div[ng-model="patient.marital_status"]').first().click()
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()           
            cy.get('div[ng-model="patient.education_level"]').first().click()
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()
            cy.get('div[ng-model="patient.financial_status"]').first().click()
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()
            cy.get('input[ng-model="patient.admission_date"]').focus().type("06/06/2017")
            cy.get('input[ng-model="patient.referral_agency"]').focus().type("Ha Noi")
            cy.get('div[ng-model="patient.province_id"]').first().click()
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()
            cy.get('div[ng-model="patient.district_id"]').first().click()
            cy.wait(delay) 
            cy.get('.select2-result-label.ui-select-choices-row-inner').first().click()
            cy.get('div[ng-model="patient.ward_id"]').first().click()
            cy.wait(delay) 
            cy.get(".select2-result-label.ui-select-choices-row-inner").first().click()
            cy.get('input[ng-model="patient.hamlet"]').focus().type("Ha Noi")
            cy.get('input[ng-model="patient.address"]').focus().type("Ha Noi")
            cy.get('div[ng-model="patient.resident_province_id"]').first().click()
            cy.wait(delay) 
            cy.get(".select2-result-label.ui-select-choices-row-inner").first().click()          
            cy.get('div[ng-model="patient.resident_district_id"]').first().click()
            cy.wait(delay) 
            cy.get(".select2-result-label.ui-select-choices-row-inner").first().click()
            cy.get('div[ng-model="patient.resident_ward_id"]').first().click()
            cy.wait(delay) 
            cy.get(".select2-result-label.ui-select-choices-row-inner").first().click()     
            cy.get('input[ng-model="patient.resident_hamlet"]').focus().type("Ha Noi")
            cy.get('input[ng-model="patient.resident_address"]').focus().type("Ha Noi")
            cy.get('div[ng-model="patient.identification_type"]').first().click()
            cy.wait(delay) 
            cy.get(".select2-result-label.ui-select-choices-row-inner").first().click()
            cy.get('input[ng-model="patient.identification_number"]').first().focus().type("123452348")
            cy.get('input[ng-model="patient.identification_issued_date"]').focus().type("07/07/2014")
            cy.get('input[ng-model="patient.identification_issued_by"]').focus().type("Ha Noi")     
      })

      it('Điền thông tin người thân', function(){
            cy.get('input[ng-model="contact.name"]').focus().type("Hoa")
            cy.get('div[ng-model="contact.contact_type"]').first().click()
            cy.wait(delay) 
            cy.get(".select2-result-label.ui-select-choices-row-inner").first().click()
            cy.get('input[ng-model="contact.address"]').focus().type("Ha Nam")
            cy.get('input[ng-model="contact.telephone"]').focus().type("098446384")
      })

      it('Lưu mới', function(){
            cy.get('.portlet-title.tabbable-line').within(function() {
                  cy.get('button[type="submit"]').click()
            })            
            cy.contains('Tạo mới thành công').should('be.visible')     
      })
})

